In [1]:
import pandas as pd
import numpy as np

In [13]:
df = pd.read_csv("../data/raw/country_vaccinations.csv")

In [ ]:
df.head()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
86507,Zimbabwe,ZWE,2022-03-25,8691642.0,4814582.0,3473523.0,139213.0,69579.0,57.59,31.90,23.02,4610.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...
86508,Zimbabwe,ZWE,2022-03-26,8791728.0,4886242.0,3487962.0,100086.0,83429.0,58.25,32.38,23.11,5528.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...
86509,Zimbabwe,ZWE,2022-03-27,8845039.0,4918147.0,3493763.0,53311.0,90629.0,58.61,32.59,23.15,6005.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...
86510,Zimbabwe,ZWE,2022-03-28,8934360.0,4975433.0,3501493.0,89321.0,100614.0,59.20,32.97,23.20,6667.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...
86511,Zimbabwe,ZWE,2022-03-29,9039729.0,5053114.0,3510256.0,105369.0,103751.0,59.90,33.48,23.26,6874.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...

In [ ]:
df.tail()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
86507,Zimbabwe,ZWE,2022-03-25,8691642.0,4814582.0,3473523.0,139213.0,69579.0,57.59,31.90,23.02,4610.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...
86508,Zimbabwe,ZWE,2022-03-26,8791728.0,4886242.0,3487962.0,100086.0,83429.0,58.25,32.38,23.11,5528.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...
86509,Zimbabwe,ZWE,2022-03-27,8845039.0,4918147.0,3493763.0,53311.0,90629.0,58.61,32.59,23.15,6005.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...
86510,Zimbabwe,ZWE,2022-03-28,8934360.0,4975433.0,3501493.0,89321.0,100614.0,59.20,32.97,23.20,6667.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...
86511,Zimbabwe,ZWE,2022-03-29,9039729.0,5053114.0,3510256.0,105369.0,103751.0,59.90,33.48,23.26,6874.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 86512 entries, 0 to 86511
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   country                              86512 non-null  str
 1   iso_code                             86512 non-null  str
 2   date                                 86512 non-null  str
 3   total_vaccinations                   43607 non-null  float64
 4   people_vaccinated                    41294 non-null  float64
 5   people_fully_vaccinated              38802 non-null  float64
 6   daily_vaccinations_raw               35362 non-null  float64
 7   daily_vaccinations                   86213 non-null  float64
 8   total_vaccinations_per_hundred       43607 non-null  float64
 9   people_vaccinated_per_hundred        41294 non-null  float64
 10  people_fully_vaccinated_per_hundred  38802 non-null  float64
 11  daily_vaccinations_per_million       86213 non-null  float64
 12  vaccines                             86512 non-null  str
 13  source_name                          86512 non-null  str
 14  source_website                       86512 non-null  str
dtypes: float64(9), str(6)
memory usage: 9.9 MB

Data Cleaning

In this section, we clean the COVID-19 vaccination dataset to prepare it for analysis. Steps include:

- Handling missing numeric values (forward fill for cumulative columns)
- Converting the date column to datetime
- Removing duplicates
- Standardizing column names
- Handling categorical data in the vaccines column
- Filtering out invalid or negative values

In [ ]:
# identifying missing values
df.isnull().sum()

country                                    0
iso_code                                   0
date                                       0
total_vaccinations                     42905
people_vaccinated                      45218
people_fully_vaccinated                47710
daily_vaccinations_raw                 51150
daily_vaccinations                       299
total_vaccinations_per_hundred         42905
people_vaccinated_per_hundred          45218
people_fully_vaccinated_per_hundred    47710
daily_vaccinations_per_million           299
vaccines                                   0
source_name                                0
source_website                             0
dtype: int64

In [22]:
# Check number and percentage of missing values
missing_count = df.isnull().sum()
missing_percent = df.isnull().mean() * 100

missing_df = pd.DataFrame({
    'missing_count': missing_count,
    'missing_percent': missing_percent
}).sort_values(by='missing_percent', ascending=False)

missing_df

                                     missing_count  missing_percent
daily_vaccinations_raw                       51150        59.124746
people_fully_vaccinated                      47710        55.148419
people_fully_vaccinated_per_hundred          47710        55.148419
people_vaccinated_per_hundred                45218        52.267893
people_vaccinated                            45218        52.267893
total_vaccinations                           42905        49.594276
total_vaccinations_per_hundred               42905        49.594276
daily_vaccinations_per_million                 299         0.345617
daily_vaccinations                             299         0.345617
date                                             0         0.000000
country                                          0         0.000000
iso_code                                         0         0.000000
vaccines                                         0         0.000000
source_name                                      0         0.000000
source_website                                   0         0.000000

Handling Missing Values
- Cumulative columns (total_vaccinations, people_vaccinated, etc.): forward-fill per country to propagate last known values, then fill any starting NaNs with 0.
- Daily columns (daily_vaccinations, daily_vaccinations_raw): fill missing values with 0 to represent days with no reported vaccinations.
- Other columns like country, date, iso_code are fully populated and require no cleaning.

In [23]:
# Cumulative columns: forward-fill then fill starting NaNs with 0
cumulative_cols = [
    'total_vaccinations', 'people_vaccinated', 'people_fully_vaccinated',
    'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
    'people_fully_vaccinated_per_hundred'
]
df[cumulative_cols] = df.groupby('country')[cumulative_cols].ffill().fillna(0)

In [24]:
# Daily columns: fill missing with 0
daily_cols = ['daily_vaccinations_raw', 'daily_vaccinations', 'daily_vaccinations_per_million']
df[daily_cols] = df[daily_cols].fillna(0)

In [ ]:
# Converting the date column to datetime
df['date'] = pd.to_datetime(df['date'])

In [25]:
# Verify missing values
df.isnull().sum()

country                                0
iso_code                               0
date                                   0
total_vaccinations                     0
people_vaccinated                      0
people_fully_vaccinated                0
daily_vaccinations_raw                 0
daily_vaccinations                     0
total_vaccinations_per_hundred         0
people_vaccinated_per_hundred          0
people_fully_vaccinated_per_hundred    0
daily_vaccinations_per_million         0
vaccines                               0
source_name                            0
source_website                         0
dtype: int64

In [34]:
# standardize column names
df.columns = [col.lower().replace(" ", "_") for col in df.columns]

In [35]:
# remove duplicates 
df = df.drop_duplicates()

In [36]:
df['vaccines'] = df['vaccines'].str.replace(', ', ',')  # normalize separators

In [37]:
df['vaccine_list'] = df['vaccines'].str.split(',')

In [39]:
#remove negative numbers
df = df[df['daily_vaccinations'] >= 0]

In [42]:
# save cleaned dataset
df.to_csv("../data/processed/country_vaccinations_clean.csv", index=False)